"""Seed maintenance templates that require user verification."""

from __future__ import annotations

from typing import Any

from .const import ATTR_SCHEDULE_DISCLAIMER

SEED_TEMPLATES: dict[str, dict[str, Any]] = {
    "subaru_outback_2024_24t_seed": {
        "id": "subaru_outback_2024_24t_seed",
        "label": "2024 Subaru Outback 2.4T (seed template)",
        "disclaimer": ATTR_SCHEDULE_DISCLAIMER,
        "items": [
            {
                "id": "engine_oil",
                "name": "Engine Oil",
                "interval_miles": 6000,
                "interval_months": 6,
                "manufacturer_anchor_miles": 6000,
                "resets_on_service": True,
                "due_soon_threshold_miles": 500,
                "overdue_threshold_miles": 0,
            },
            {
                "id": "engine_oil_filter",
                "name": "Engine Oil Filter",
                "interval_miles": 6000,
                "interval_months": 6,
                "manufacturer_anchor_miles": 6000,
                "resets_on_service": True,
                "due_soon_threshold_miles": 500,
                "overdue_threshold_miles": 0,
            },
            {
                "id": "spark_plug",
                "name": "Spark Plug",
                "interval_miles": 60000,
                "interval_months": 60,
                "manufacturer_anchor_miles": 60000,
                "resets_on_service": True,
                "due_soon_threshold_miles": 1000,
                "overdue_threshold_miles": 0,
            },
            {
                "id": "drive_belts",
                "name": "Drive Belt(s)",
                "interval_miles": 30000,
                "interval_months": 30,
                "manufacturer_anchor_miles": 30000,
                "resets_on_service": True,
                "due_soon_threshold_miles": 1000,
                "overdue_threshold_miles": 0,
            },
            {
                "id": "fuel_systems_lines_connections",
                "name": "Fuel Systems, Lines & Connections",
                "interval_miles": 30000,
                "interval_months": 30,
                "manufacturer_anchor_miles": 30000,
                "resets_on_service": True,
                "due_soon_threshold_miles": 1000,
                "overdue_threshold_miles": 0,
            },
            {
                "id": "fuel_filter",
                "name": "Fuel Filter",
                "interval_miles": 72000,
                "interval_months": 72,
                "manufacturer_anchor_miles": 72000,
                "resets_on_service": True,
                "due_soon_threshold_miles": 1000,
                "overdue_threshold_miles": 0,
            },
            {
                "id": "air_cleaner_element",
                "name": "Air Cleaner Element",
                "interval_miles": 30000,
                "interval_months": 30,
                "manufacturer_anchor_miles": 30000,
                "resets_on_service": True,
                "due_soon_threshold_miles": 1000,
                "overdue_threshold_miles": 0,
            },
            {
                "id": "cooling_system_hoses_connections",
                "name": "Cooling System, Hoses & Connections",
                "interval_miles": 30000,
                "interval_months": 30,
                "manufacturer_anchor_miles": 30000,
                "resets_on_service": True,
                "due_soon_threshold_miles": 1000,
                "overdue_threshold_miles": 0,
            },
            {
                "id": "clutch_operation",
                "name": "Clutch Operation",
                "interval_miles": 12000,
                "interval_months": 12,
                "manufacturer_anchor_miles": 12000,
                "resets_on_service": True,
                "due_soon_threshold_miles": 1000,
                "overdue_threshold_miles": 0,
            },
            {
                "id": "transmission_gear_oil",
                "name": "Transmission Gear Oil",
                "interval_miles": 30000,
                "interval_months": 30,
                "manufacturer_anchor_miles": 30000,
                "resets_on_service": False,
                "due_soon_threshold_miles": 1000,
                "overdue_threshold_miles": 0,
            },
            {
                "id": "cvt_fluid",
                "name": "CVT Fluid",
                "interval_miles": 30000,
                "interval_months": 30,
                "manufacturer_anchor_miles": 30000,
                "resets_on_service": False,
                "due_soon_threshold_miles": 1000,
                "overdue_threshold_miles": 0,
            },
            {
                "id": "differential_gear_oil",
                "name": "Front & Rear Differential Gear Oil",
                "interval_miles": 30000,
                "interval_months": 30,
                "manufacturer_anchor_miles": 30000,
                "resets_on_service": False,
                "due_soon_threshold_miles": 1000,
                "overdue_threshold_miles": 0,
            },
            {
                "id": "brake_lines_and_systems",
                "name": "Brake Lines / Parking & Service Brake Systems",
                "interval_miles": 12000,
                "interval_months": 12,
                "manufacturer_anchor_miles": 12000,
                "resets_on_service": True,
                "due_soon_threshold_miles": 1000,
                "overdue_threshold_miles": 0,
            },
            {
                "id": "brake_fluid",
                "name": "Brake Fluid",
                "interval_miles": 30000,
                "interval_months": 30,
                "manufacturer_anchor_miles": 30000,
                "resets_on_service": True,
                "due_soon_threshold_miles": 1000,
                "overdue_threshold_miles": 0,
            },
            {
                "id": "brake_pads_discs_axle_boots_joints",
                "name": "Disc Brake Pad / Disc / Axle Boots & Joints",
                "interval_miles": 12000,
                "interval_months": 12,
                "manufacturer_anchor_miles": 12000,
                "resets_on_service": True,
                "due_soon_threshold_miles": 1000,
                "overdue_threshold_miles": 0,
            },
            {
                "id": "steering_and_suspension",
                "name": "Steering & Suspension",
                "interval_miles": 12000,
                "interval_months": 12,
                "manufacturer_anchor_miles": 12000,
                "resets_on_service": True,
                "due_soon_threshold_miles": 1000,
                "overdue_threshold_miles": 0,
            },
            {
                "id": "wheel_bearing",
                "name": "Wheel Bearing",
                "interval_miles": 60000,
                "interval_months": 60,
                "manufacturer_anchor_miles": 60000,
                "resets_on_service": True,
                "due_soon_threshold_miles": 1000,
                "overdue_threshold_miles": 0,
            },
            {
                "id": "rotate_and_inspect_tires",
                "name": "Rotate & Inspect Tires",
                "interval_miles": 6000,
                "interval_months": 6,
                "manufacturer_anchor_miles": 6000,
                "resets_on_service": True,
                "due_soon_threshold_miles": 500,
                "overdue_threshold_miles": 0,
            },
            {
                "id": "hvac_filter",
                "name": "HVAC System A/C Filter",
                "interval_miles": 12000,
                "interval_months": 12,
                "manufacturer_anchor_miles": 12000,
                "resets_on_service": True,
                "due_soon_threshold_miles": 1000,
                "overdue_threshold_miles": 0,
            },
        ],
    },
    "mazda_cx5_2021_25_seed": {
        "id": "mazda_cx5_2021_25_seed",
        "label": "2021 Mazda CX-5 2.5 (seed template)",
        "disclaimer": ATTR_SCHEDULE_DISCLAIMER,
        "items": [
            {
                "id": "engine_oil",
                "name": "Engine Oil",
                "interval_miles": 7500,
                "interval_months": 12,
                "manufacturer_anchor_miles": 7500,
                "resets_on_service": True,
                "due_soon_threshold_miles": 500,
                "overdue_threshold_miles": 0,
            },
            {
                "id": "air_filter",
                "name": "Air Filter",
                "interval_miles": 30000,
                "interval_months": 48,
                "manufacturer_anchor_miles": 30000,
                "resets_on_service": True,
                "due_soon_threshold_miles": 1000,
                "overdue_threshold_miles": 0,
            },
            {
                "id": "drive_belts",
                "name": "Drive Belts",
                "interval_miles": 30000,
                "interval_months": 48,
                "manufacturer_anchor_miles": 30000,
                "resets_on_service": True,
                "due_soon_threshold_miles": 1000,
                "overdue_threshold_miles": 0,
            },
            {
                "id": "fuel_lines_and_hoses",
                "name": "Fuel Lines and Hoses",
                "interval_miles": 15000,
                "interval_months": 24,
                "manufacturer_anchor_miles": 15000,
                "resets_on_service": True,
                "due_soon_threshold_miles": 1000,
                "overdue_threshold_miles": 0,
            },
            {
                "id": "brake_lines_hoses_connections",
                "name": "Brake Lines, Hoses and Connections",
                "interval_miles": 7500,
                "interval_months": 12,
                "manufacturer_anchor_miles": 7500,
                "resets_on_service": True,
                "due_soon_threshold_miles": 500,
                "overdue_threshold_miles": 0,
            },
            {
                "id": "disc_brakes",
                "name": "Disc Brakes",
                "interval_miles": 7500,
                "interval_months": 12,
                "manufacturer_anchor_miles": 7500,
                "resets_on_service": True,
                "due_soon_threshold_miles": 500,
                "overdue_threshold_miles": 0,
            },
            {
                "id": "tire_rotation",
                "name": "Tire Rotation",
                "interval_miles": 7500,
                "interval_months": 12,
                "manufacturer_anchor_miles": 7500,
                "resets_on_service": True,
                "due_soon_threshold_miles": 500,
                "overdue_threshold_miles": 0,
            },
            {
                "id": "steering_operation_and_linkages",
                "name": "Steering Operation and Linkages",
                "interval_miles": 15000,
                "interval_months": 24,
                "manufacturer_anchor_miles": 15000,
                "resets_on_service": True,
                "due_soon_threshold_miles": 1000,
                "overdue_threshold_miles": 0,
            },
            {
                "id": "suspension_and_wheel_bearing",
                "name": "Front/Rear Suspension and Wheel Bearing Axial Play",
                "interval_miles": 15000,
                "interval_months": 24,
                "manufacturer_anchor_miles": 15000,
                "resets_on_service": True,
                "due_soon_threshold_miles": 1000,
                "overdue_threshold_miles": 0,
            },
            {
                "id": "driveshaft_dust_boots",
                "name": "Driveshaft Dust Boots",
                "interval_miles": 15000,
                "interval_months": 24,
                "manufacturer_anchor_miles": 15000,
                "resets_on_service": True,
                "due_soon_threshold_miles": 1000,
                "overdue_threshold_miles": 0,
            },
            {
                "id": "chassis_body_bolts_and_nuts",
                "name": "Bolts and Nuts on Chassis and Body",
                "interval_miles": 15000,
                "interval_months": 24,
                "manufacturer_anchor_miles": 15000,
                "resets_on_service": True,
                "due_soon_threshold_miles": 1000,
                "overdue_threshold_miles": 0,
            },
            {
                "id": "exhaust_system_and_heat_shields",
                "name": "Exhaust System and Heat Shields",
                "interval_miles": 60000,
                "interval_months": 96,
                "manufacturer_anchor_miles": 60000,
                "resets_on_service": True,
                "due_soon_threshold_miles": 1000,
                "overdue_threshold_miles": 0,
            },
            {
                "id": "cabin_air_filter",
                "name": "Cabin Air Filter",
                "interval_miles": 30000,
                "interval_months": 24,
                "manufacturer_anchor_miles": 30000,
                "resets_on_service": True,
                "due_soon_threshold_miles": 1000,
                "overdue_threshold_miles": 0,
            }
        ],
    },
}
